"""Intent parsing: turn a free-text WhatsApp message into structured JSON.

Returns a dict matching:
{
  "action":    "add" | "remove" | "list" | "complete" | "schedule" | "clarify",
  "list_name": str | null,
  "items":     [str, ...],
  "when":      ISO-8601 datetime | null,
  "scope":     "me" | "us" | null,
  "reply":     str   # human-friendly confirmation, generated by Claude
}
"""
import json
from anthropic import Anthropic

client = Anthropic()
MODEL = "claude-haiku-4-5-20251001"

SYSTEM = """You are the intent parser for Yaadi, a household assistant.
Return ONLY valid JSON, no prose, no code fences.

Schema:
{
  "action": "add" | "remove" | "list" | "complete" | "schedule" | "clarify",
  "list_name": "<existing list, a new name, or null>",
  "items": ["..."],
  "when": "<ISO 8601 datetime or null>",
  "scope": "me" | "us" | null,
  "reply": "<warm, concise confirmation with item counts when relevant>"
}

Rules:
- If the user names a list that does not exist, set action="clarify" and ask in
  "reply" whether to create it.
- For ambiguous targets ("add milk" with no list), set action="clarify".
- Resolve relative times ("tomorrow 6pm", "tuesday") using the provided current_time.
- "remind us" → scope "us"; "remind me" → scope "me".
- Keep "reply" short and friendly. Sentence case. No emoji unless natural.
"""


def parse_intent(message: str, list_names: list[str], current_time_iso: str) -> dict:
    context = (
        f"Existing lists: {list_names}\n"
        f"Current time: {current_time_iso}\n"
        f"User said: {message}"
    )
    resp = client.messages.create(
        model=MODEL,
        max_tokens=400,
        system=SYSTEM,
        messages=[{"role": "user", "content": context}],
    )
    text = resp.content[0].text.strip()
    if text.startswith("```"):
        text = text.split("```")[1].lstrip("json").strip()
    return json.loads(text)
